### ISSUE TITLE
Πρόγραμμα μαθημάτων

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#114]
### Δήλωση Θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @provopoulos 
- Σχετικά θέματα: #124 

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by AsteriosP** [comment]
θα ήθελα να προτείνω μία δομή δεδομένων για το πρόγραμμα.

σε ένα αρχείο `timetable.yml` στο φάκελο `_data` το όποιο να περιέχει πολλαπλές δομές με ονόματα από το εκάστοτε εξάμηνο πχ. `under_sem_<sem_id>` το `sem_id` μπορεί να είναι στο "εύρος" [1 - 8] για το προπτυχιακό και μπορούν φυσικά να προστεθούν αντίστοιχα και τα υπόλοιπα προγράμματα του τμήματος. 

Μέσα σε αυτές τις δομές μπορεί να έχει όλες τις διαλέξεις του εξάμηνου. Για κάθε διάλεξη πρέπει να περιέχεται η ήμερα (`day`) που γίνεται, η ώρα που γίνεται (`time`), το όνομα του μαθήματος (`title`), ο καθηγητής που το κάνει (`person`) και η αίθουσα/αμφιθέατρο που πραγματοποιείται (`location`). 
Παρακάτω φαίνεται ένα μέρος αυτής της δομής για το μάθημα «Πιθανότητες» του 2ου εξαμήνου. 

```yaml
under_sem_2:
  - day: "Δευτέρα"
    time: 9
    title: "Πιθανότητεςa"
    person: "alex"
    location: "Εργαστήριο Γαληνός"
  - day: "Δευτέρα"
    time: 11
    title: "Πιθανότητεςb"
    person: "avlonitis"
    location: "Αμφιθέατρο 2"
  - day: "Τετάρτη"
    time: 11
    title: "Πιθανότητεςc"
    person: "alex"
    location: "Εργαστήριο Γαληνός"
  - day: "Παρασκευή"
    time: 11
    title: "Πιθανότητεςd"
    person: "avlonitis"
    location: "Αμφιθέατρο 2"
```
